/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import javax.swing.ImageIcon;

/**
 
 * @author Gabriel Cabrera
 */
public class Login extends javax.swing.JFrame {
        int primerclickuser=0;
        int primerclickclave=0;
        int xMouse,yMouse;
    /**
     * Creates new form Login
     */
        
    public Login() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/login/imagenes/logo_150px.png")).getImage()); //cambiar icono
        LOGO.requestFocusInWindow(); //hacer que no se focusee el textfield usuario ni bien abrir el programa
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Logueo = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        BarraUsuario = new javax.swing.JPanel();
        imagenuser = new javax.swing.JLabel();
        textfielduser = new javax.swing.JTextField();
        BarraClave = new javax.swing.JPanel();
        imagenclave = new javax.swing.JLabel();
        passwordfieldclave = new javax.swing.JPasswordField();
        BotonSalir = new javax.swing.JPanel();
        imagenX = new javax.swing.JLabel();
        BotonEntrar = new javax.swing.JPanel();
        botonIniciarSesion = new javax.swing.JLabel();
        BotonRegistrarse = new javax.swing.JPanel();
        botonRegistrarse = new javax.swing.JLabel();
        LOGO = new javax.swing.JLabel();
        clavesave = new javax.swing.JLabel();
        usersave = new javax.swing.JLabel();
        BotonSalir1 = new javax.swing.JPanel();
        imagenX1 = new javax.swing.JLabel();
        ganzerrainfo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login - Gazerra");
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logueo.setBackground(new java.awt.Color(48, 52, 69));
        Logueo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(247, 125, 52));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        Logueo.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 10));

        BarraUsuario.setBackground(new java.awt.Color(255, 255, 255));

        imagenuser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagenuser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/imagenes/icons8_User_Male_35px.png"))); // NOI18N

        textfielduser.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        textfielduser.setForeground(new java.awt.Color(163, 163, 163));
        textfielduser.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        textfielduser.setText("Usuario");
        textfielduser.setBorder(null);
        textfielduser.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textfielduser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textfielduserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textfielduserFocusLost(evt);
            }
        });

        javax.swing.GroupLayout BarraUsuarioLayout = new javax.swing.GroupLayout(BarraUsuario);
        BarraUsuario.setLayout(BarraUsuarioLayout);
        BarraUsuarioLayout.setHorizontalGroup(
            BarraUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarraUsuarioLayout.createSequentialGroup()
                .addComponent(imagenuser, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textfielduser, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE))
        );
        BarraUsuarioLayout.setVerticalGroup(
            BarraUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagenuser, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(textfielduser, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        Logueo.add(BarraUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 290, 50));

        BarraClave.setBackground(new java.awt.Color(255, 255, 255));

        imagenclave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagenclave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/imagenes/icons8_Lock_35px_4.png"))); // NOI18N
        imagenclave.setAutoscrolls(true);

        passwordfieldclave.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        passwordfieldclave.setForeground(new java.awt.Color(163, 163, 163));
        passwordfieldclave.setText("Contraseña");
        passwordfieldclave.setBorder(null);
        passwordfieldclave.setEchoChar('\u2022');
        passwordfieldclave.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordfieldclaveFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordfieldclaveFocusLost(evt);
            }
        });

        javax.swing.GroupLayout BarraClaveLayout = new javax.swing.GroupLayout(BarraClave);
        BarraClave.setLayout(BarraClaveLayout);
        BarraClaveLayout.setHorizontalGroup(
            BarraClaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarraClaveLayout.createSequentialGroup()
                .addComponent(imagenclave, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordfieldclave, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE))
        );
        BarraClaveLayout.setVerticalGroup(
            BarraClaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagenclave, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(passwordfieldclave, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        Logueo.add(BarraClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 290, 50));

        BotonSalir.setBackground(new java.awt.Color(247, 125, 52));
        BotonSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonSalirMouseExited(evt);
            }
        });

        imagenX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagenX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/imagenes/icons8_Delete_17px.png"))); // NOI18N
        imagenX.setFocusable(false);

        javax.swing.GroupLayout BotonSalirLayout = new javax.swing.GroupLayout(BotonSalir);
        BotonSalir.setLayout(BotonSalirLayout);
        BotonSalirLayout.setHorizontalGroup(
            BotonSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagenX, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
        );
        BotonSalirLayout.setVerticalGroup(
            BotonSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagenX, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
        );

        Logueo.add(BotonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 20, 20));

        BotonEntrar.setBackground(new java.awt.Color(247, 125, 52));
        BotonEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonEntrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonEntrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonEntrarMouseExited(evt);
            }
        });

        botonIniciarSesion.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        botonIniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        botonIniciarSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botonIniciarSesion.setText("Iniciar sesión");
        botonIniciarSesion.setFocusable(false);

        javax.swing.GroupLayout BotonEntrarLayout = new javax.swing.GroupLayout(BotonEntrar);
        BotonEntrar.setLayout(BotonEntrarLayout);
        BotonEntrarLayout.setHorizontalGroup(
            BotonEntrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonIniciarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        BotonEntrarLayout.setVerticalGroup(
            BotonEntrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonIniciarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        Logueo.add(BotonEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 140, 40));

        BotonRegistrarse.setBackground(new java.awt.Color(0, 183, 46));
        BotonRegistrarse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonRegistrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonRegistrarseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonRegistrarseMouseExited(evt);
            }
        });

        botonRegistrarse.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        botonRegistrarse.setForeground(new java.awt.Color(255, 255, 255));
        botonRegistrarse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botonRegistrarse.setText("Registrarse");
        botonRegistrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonRegistrarseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonRegistrarseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonRegistrarseMouseExited(evt);
            }
        });

        javax.swing.GroupLayout BotonRegistrarseLayout = new javax.swing.GroupLayout(BotonRegistrarse);
        BotonRegistrarse.setLayout(BotonRegistrarseLayout);
        BotonRegistrarseLayout.setHorizontalGroup(
            BotonRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonRegistrarse, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        BotonRegistrarseLayout.setVerticalGroup(
            BotonRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonRegistrarse, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        Logueo.add(BotonRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, -1, -1));

        LOGO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/imagenes/logo_127px.png"))); // NOI18N
        Logueo.add(LOGO, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        clavesave.setForeground(new java.awt.Color(48, 52, 69));
        Logueo.add(clavesave, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, -1, -1));

        usersave.setForeground(new java.awt.Color(48, 52, 69));
        Logueo.add(usersave, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, -1, -1));

        BotonSalir1.setBackground(new java.awt.Color(247, 125, 52));
        BotonSalir1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonSalir1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonSalir1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonSalir1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonSalir1MouseExited(evt);
            }
        });
        BotonSalir1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imagenX1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagenX1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/imagenes/icons8_Horizontal_Line_17px_1.png"))); // NOI18N
        imagenX1.setFocusable(false);
        BotonSalir1.add(imagenX1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 0, -1, 20));

        Logueo.add(BotonSalir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 10, 22, 20));

        ganzerrainfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ganzerrainfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/imagenes/ganzerra_marcadeagua.png"))); // NOI18N
        ganzerrainfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ganzerrainfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ganzerrainfoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ganzerrainfoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ganzerrainfoMouseExited(evt);
            }
        });
        Logueo.add(ganzerrainfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 180, 170, 60));

        getContentPane().add(Logueo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSalirMouseEntered
    BotonSalir.setBackground(new java.awt.Color(255,159,101)); //brillo del boton de salir al tocar mouse
    }//GEN-LAST:event_BotonSalirMouseEntered

    private void BotonSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSalirMouseExited
    BotonSalir.setBackground(new java.awt.Color(247,125,52));       // se va el brillo cuando se va el mouse
    }//GEN-LAST:event_BotonSalirMouseExited

    private void textfielduserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textfielduserFocusGained
    if (primerclickuser == 0){   //si es la primera vez que se clickea
    textfielduser.setForeground(new java.awt.Color(30, 30, 30)); //pinta de negro el texto
    textfielduser.setText("");  //se borra el texto
    primerclickuser=1;          //y se establece que ya no es la primera vez
   }
    }//GEN-LAST:event_textfielduserFocusGained

    private void passwordfieldclaveFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordfieldclaveFocusGained
    if (primerclickclave == 0){
    passwordfieldclave.setForeground(new java.awt.Color(30, 30, 30)); //pinta de negro el texto
    passwordfieldclave.setText("");
    primerclickclave=1;
    }
    }//GEN-LAST:event_passwordfieldclaveFocusGained

    private void BotonSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSalirMouseClicked
        System.exit(0);        // salir al clickear
    }//GEN-LAST:event_BotonSalirMouseClicked

    private void BotonEntrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonEntrarMouseEntered
        BotonEntrar.setBackground(new java.awt.Color(255,159,101));
    }//GEN-LAST:event_BotonEntrarMouseEntered

    private void BotonEntrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonEntrarMouseExited
        BotonEntrar.setBackground(new java.awt.Color(247,125,52)); 
    }//GEN-LAST:event_BotonEntrarMouseExited

    private void BotonRegistrarseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonRegistrarseMouseEntered
        BotonRegistrarse.setBackground(new java.awt.Color(20,255,79));
    }//GEN-LAST:event_BotonRegistrarseMouseEntered

    private void BotonRegistrarseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonRegistrarseMouseExited
        BotonRegistrarse.setBackground(new java.awt.Color(0,183,46)); 
    }//GEN-LAST:event_BotonRegistrarseMouseExited

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // TODO add your handling code here:
        int x=evt.getXOnScreen();               //crea una variable para usar luego en el mouse con los valores de X
        int y=evt.getYOnScreen();               //crea una variable para usar luego en el mouse con los valores Y
        this.setLocation(x-xMouse, y-yMouse);   /*a los valores anteriores que estaban basados en 0,0, se les resta los valores
        calculados debajo para así al mover, se mueva la ventana desde la posición del mouse
        */
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:
       xMouse=evt.getX(); //tomar posicion X y enviarlo a xMouse
       yMouse=evt.getY();  //tomar posicion Y y enviarlo a yMouse
       
    }//GEN-LAST:event_jPanel2MousePressed

    private void textfielduserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textfielduserFocusLost
    String dato;
    dato = this.textfielduser.getText();
    if ("".equals(dato)){       //si no hay nada escrito
        textfielduser.setForeground(new java.awt.Color(163, 163, 163)); //pinta de gris el texto
        textfielduser.setText("Usuario"); //se vuelve a escribir usuario
        primerclickuser=0;      //se reinicia el primer click para automaticamente borrar en click
    }
    }//GEN-LAST:event_textfielduserFocusLost

    private void passwordfieldclaveFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordfieldclaveFocusLost
    String pass = "";
    char [] password = passwordfieldclave.getPassword();
    for(int x=0; x<password.length; x++){
        pass+=password[x];
    }
    if ("".equals(pass)){       //si no hay nada escrito
        passwordfieldclave.setForeground(new java.awt.Color(163, 163, 163)); //pinta de gris el texto
        passwordfieldclave.setText("Contraseña"); //se vuelve a escribir usuario
        primerclickclave=0;      //se reinicia el primer click para automaticamente borrar en click
    }
    }//GEN-LAST:event_passwordfieldclaveFocusLost

    private void botonRegistrarseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegistrarseMouseClicked
    Registro registro=new Registro();
    registro.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_botonRegistrarseMouseClicked

    private void botonRegistrarseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegistrarseMouseEntered
    BotonRegistrarse.setBackground(new java.awt.Color(0,224,56));
    }//GEN-LAST:event_botonRegistrarseMouseEntered

    private void botonRegistrarseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegistrarseMouseExited
    BotonRegistrarse.setBackground(new java.awt.Color(0,183,46));
    }//GEN-LAST:event_botonRegistrarseMouseExited

    private void BotonEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonEntrarMouseClicked
    LOGO.requestFocusInWindow();
    String valorPass = new String(passwordfieldclave.getPassword());
    LogueadoUsuario LogueadoUsuario=new LogueadoUsuario();
    LogueadoAdmin LogueadoAdmin = new LogueadoAdmin();
    if (textfielduser.getText().equals("admin") && valorPass.equals("admin")){
        System.out.println("Se ha logueado como administrador");
        LogueadoAdmin.setVisible(true);
        this.dispose();
    }else{

    if (textfielduser.getText().equalsIgnoreCase(usersave.getText()) && valorPass.equals(clavesave.getText())){ //comparar ignorando mayúsuclas en el nombre
        LogueadoUsuario.setVisible(true);
        System.out.println("Se ha logueado como usuario");
        this.dispose();
    }else{
    if (textfielduser.getText().equalsIgnoreCase("Usuario") || passwordfieldclave.getPassword().equals("Contraseña") || textfielduser.getText().equalsIgnoreCase("") || passwordfieldclave.getPassword().equals("")){
        new Error1(this, true).setVisible(true);///////////////////
        System.out.println("Debe llenar todos los campos");
    }else{  
        new Error9(this, true).setVisible(true);///////////////////
        System.out.println("El usuario y la clave no coinciden");
    }
    }
    }
    }//GEN-LAST:event_BotonEntrarMouseClicked

    private void BotonSalir1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSalir1MouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_BotonSalir1MouseClicked

    private void BotonSalir1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSalir1MouseEntered
        BotonSalir1.setBackground(new java.awt.Color(255,159,101)); //brillo del boton de salir al tocar mouse
    }//GEN-LAST:event_BotonSalir1MouseEntered

    private void BotonSalir1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSalir1MouseExited
        BotonSalir1.setBackground(new java.awt.Color(247,125,52));       // se va el brillo cuando se va el mouse
    }//GEN-LAST:event_BotonSalir1MouseExited

    private void ganzerrainfoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ganzerrainfoMouseEntered
        ganzerrainfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/imagenes/ganzerra_marcadeagua.glow.png")));
    }//GEN-LAST:event_ganzerrainfoMouseEntered

    private void ganzerrainfoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ganzerrainfoMouseExited
        ganzerrainfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/imagenes/ganzerra_marcadeagua.png")));
    }//GEN-LAST:event_ganzerrainfoMouseExited

    private void ganzerrainfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ganzerrainfoMouseClicked
        PopupLogin popup = new PopupLogin();
        popup.setVisible(true);
    }//GEN-LAST:event_ganzerrainfoMouseClicked
        /**
     * @param args the command line arguments [0,183,46]
     */
    
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BarraClave;
    private javax.swing.JPanel BarraUsuario;
    private javax.swing.JPanel BotonEntrar;
    private javax.swing.JPanel BotonRegistrarse;
    private javax.swing.JPanel BotonSalir;
    private javax.swing.JPanel BotonSalir1;
    private javax.swing.JLabel LOGO;
    private javax.swing.JPanel Logueo;
    private javax.swing.JLabel botonIniciarSesion;
    private javax.swing.JLabel botonRegistrarse;
    public static javax.swing.JLabel clavesave;
    private javax.swing.JLabel ganzerrainfo;
    private javax.swing.JLabel imagenX;
    private javax.swing.JLabel imagenX1;
    private javax.swing.JLabel imagenclave;
    private javax.swing.JLabel imagenuser;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField passwordfieldclave;
    public javax.swing.JTextField textfielduser;
    public static javax.swing.JLabel usersave;
    // End of variables declaration//GEN-END:variables
}
