/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import javax.swing.ImageIcon;

/**
 *
 * @author Gabriel Cabrera
 */
public class LogueadoAdmin extends javax.swing.JFrame {
    int xMouse,yMouse;
    /**
     * Creates new form Logueado
     */
    public LogueadoAdmin() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/login/imagenes/logo_150px.png")).getImage()); //cambiar icono
        logo.requestFocusInWindow();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLateral = new javax.swing.JPanel();
        Logo = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        BotonSalir = new javax.swing.JPanel();
        imagenX = new javax.swing.JLabel();
        Fondo = new javax.swing.JPanel();
        Boton = new javax.swing.JPanel();
        Icono = new javax.swing.JLabel();
        Texto = new javax.swing.JLabel();
        CerrarSesion = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Boton1 = new javax.swing.JPanel();
        Icono1 = new javax.swing.JLabel();
        Texto1 = new javax.swing.JLabel();
        Boton2 = new javax.swing.JPanel();
        Icono2 = new javax.swing.JLabel();
        Texto2 = new javax.swing.JLabel();
        Boton3 = new javax.swing.JPanel();
        Icono3 = new javax.swing.JLabel();
        Texto3 = new javax.swing.JLabel();
        Boton4 = new javax.swing.JPanel();
        Icono4 = new javax.swing.JLabel();
        Texto4 = new javax.swing.JLabel();
        Boton5 = new javax.swing.JPanel();
        Icono5 = new javax.swing.JLabel();
        Texto5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Panel - Gazerra");
        setBackground(new java.awt.Color(48, 52, 69));
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelLateral.setBackground(new java.awt.Color(247, 125, 52));
        panelLateral.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelLateralMouseDragged(evt);
            }
        });
        panelLateral.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelLateralMousePressed(evt);
            }
        });

        javax.swing.GroupLayout panelLateralLayout = new javax.swing.GroupLayout(panelLateral);
        panelLateral.setLayout(panelLateralLayout);
        panelLateralLayout.setHorizontalGroup(
            panelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        panelLateralLayout.setVerticalGroup(
            panelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(panelLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 10));

        Logo.setBackground(new java.awt.Color(247, 125, 52));
        Logo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/imagenes/logo_127px.png"))); // NOI18N
        Logo.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        getContentPane().add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 150, 490));

        BotonSalir.setBackground(new java.awt.Color(247, 125, 52));
        BotonSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonSalirMouseExited(evt);
            }
        });
        BotonSalir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imagenX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagenX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/imagenes/icons8_Horizontal_Line_17px_1.png"))); // NOI18N
        imagenX.setFocusable(false);
        BotonSalir.add(imagenX, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 0, -1, 20));

        getContentPane().add(BotonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(878, 10, 22, 20));

        Fondo.setBackground(new java.awt.Color(48, 52, 69));
        Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Boton.setBackground(new java.awt.Color(247, 125, 52));
        Boton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotonMousePressed(evt);
            }
        });
        Boton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Icono.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Icono.setForeground(new java.awt.Color(255, 255, 255));
        Icono.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panelimagenes/icons8_Male_User_100px_1.png"))); // NOI18N
        Icono.setFocusable(false);
        Boton.add(Icono, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 190));

        Texto.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        Texto.setForeground(new java.awt.Color(255, 255, 255));
        Texto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Texto.setText("USUARIOS");
        Texto.setFocusable(false);
        Boton.add(Texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 210, 30));

        Fondo.add(Boton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 210, 210));

        CerrarSesion.setBackground(new java.awt.Color(102, 102, 102));
        CerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CerrarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CerrarSesionMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CerrarSesionMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cerrar sesión");

        javax.swing.GroupLayout CerrarSesionLayout = new javax.swing.GroupLayout(CerrarSesion);
        CerrarSesion.setLayout(CerrarSesionLayout);
        CerrarSesionLayout.setHorizontalGroup(
            CerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        CerrarSesionLayout.setVerticalGroup(
            CerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
        );

        Fondo.add(CerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, -1, 20));

        Boton1.setBackground(new java.awt.Color(247, 125, 52));
        Boton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Boton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Boton1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Boton1MousePressed(evt);
            }
        });
        Boton1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Icono1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Icono1.setForeground(new java.awt.Color(255, 255, 255));
        Icono1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Icono1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panelimagenes/icons8_Assistant_85px.png"))); // NOI18N
        Icono1.setFocusable(false);
        Boton1.add(Icono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 170));

        Texto1.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        Texto1.setForeground(new java.awt.Color(255, 255, 255));
        Texto1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Texto1.setText("TRABAJADORES");
        Texto1.setFocusable(false);
        Boton1.add(Texto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 210, 30));

        Fondo.add(Boton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 210, 190));

        Boton2.setBackground(new java.awt.Color(247, 125, 52));
        Boton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Boton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Boton2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Boton2MousePressed(evt);
            }
        });
        Boton2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Icono2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Icono2.setForeground(new java.awt.Color(255, 255, 255));
        Icono2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Icono2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panelimagenes/icons8_Car_Service_100px.png"))); // NOI18N
        Icono2.setFocusable(false);
        Boton2.add(Icono2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 190));

        Texto2.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        Texto2.setForeground(new java.awt.Color(255, 255, 255));
        Texto2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Texto2.setText("COCHES");
        Texto2.setFocusable(false);
        Boton2.add(Texto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 210, 30));

        Fondo.add(Boton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 70, 210, 210));

        Boton3.setBackground(new java.awt.Color(247, 125, 52));
        Boton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Boton3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Boton3MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Boton3MousePressed(evt);
            }
        });
        Boton3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Icono3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Icono3.setForeground(new java.awt.Color(255, 255, 255));
        Icono3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Icono3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panelimagenes/icons8_Bus_85px.png"))); // NOI18N
        Icono3.setFocusable(false);
        Boton3.add(Icono3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 150));

        Texto3.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        Texto3.setForeground(new java.awt.Color(255, 255, 255));
        Texto3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Texto3.setText("LÍNEAS");
        Texto3.setFocusable(false);
        Boton3.add(Texto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 210, 30));

        Fondo.add(Boton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 290, 210, 170));

        Boton4.setBackground(new java.awt.Color(247, 125, 52));
        Boton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Boton4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Boton4MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Boton4MousePressed(evt);
            }
        });
        Boton4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Icono4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Icono4.setForeground(new java.awt.Color(255, 255, 255));
        Icono4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Icono4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panelimagenes/icons8_Settings_85px.png"))); // NOI18N
        Icono4.setFocusable(false);
        Boton4.add(Icono4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 170));

        Texto4.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        Texto4.setForeground(new java.awt.Color(255, 255, 255));
        Texto4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Texto4.setText("AJUSTES");
        Texto4.setFocusable(false);
        Boton4.add(Texto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 210, 30));

        Fondo.add(Boton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, 210, 190));

        Boton5.setBackground(new java.awt.Color(247, 125, 52));
        Boton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Boton5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Boton5MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Boton5MousePressed(evt);
            }
        });
        Boton5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Icono5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Icono5.setForeground(new java.awt.Color(255, 255, 255));
        Icono5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Icono5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panelimagenes/icons8_Driver_100px.png"))); // NOI18N
        Icono5.setFocusable(false);
        Boton5.add(Icono5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 150));

        Texto5.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        Texto5.setForeground(new java.awt.Color(255, 255, 255));
        Texto5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Texto5.setText("ASIGNAR");
        Texto5.setFocusable(false);
        Boton5.add(Texto5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 210, 30));

        Fondo.add(Boton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 210, 170));

        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelLateralMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelLateralMouseDragged
        int x=evt.getXOnScreen();               //crea una variable para usar luego en el mouse con los valores de X
        int y=evt.getYOnScreen();               //crea una variable para usar luego en el mouse con los valores Y
        this.setLocation(x-xMouse, y-yMouse);        // TODO add your handling code here:
    }//GEN-LAST:event_panelLateralMouseDragged

    private void panelLateralMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelLateralMousePressed
        xMouse=evt.getX(); //tomar posicion X y enviarlo a xMouse
        yMouse=evt.getY();  //tomar posicion Y y enviarlo a yMouse
    }//GEN-LAST:event_panelLateralMousePressed

    private void BotonSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSalirMouseClicked
     this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_BotonSalirMouseClicked

    private void BotonSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSalirMouseEntered
        BotonSalir.setBackground(new java.awt.Color(255,159,101)); //brillo del boton de salir al tocar mouse
    }//GEN-LAST:event_BotonSalirMouseEntered

    private void BotonSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSalirMouseExited
        BotonSalir.setBackground(new java.awt.Color(247,125,52));       // se va el brillo cuando se va el mouse
    }//GEN-LAST:event_BotonSalirMouseExited

    private void BotonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonMouseEntered
        Boton.setBackground(new java.awt.Color(255,159,101));
    }//GEN-LAST:event_BotonMouseEntered

    private void BotonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonMouseExited
        Boton.setBackground(new java.awt.Color(247,125,52));
    }//GEN-LAST:event_BotonMouseExited

    private void BotonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonMousePressed

    private void CerrarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarSesionMouseEntered
        CerrarSesion.setBackground(new java.awt.Color(150,150,150));
        jLabel1.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_CerrarSesionMouseEntered

    private void CerrarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarSesionMouseExited
        CerrarSesion.setBackground(new java.awt.Color(102,102,102));
        jLabel1.setForeground(new java.awt.Color(153,153,153));
    }//GEN-LAST:event_CerrarSesionMouseExited

    private void CerrarSesionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarSesionMousePressed
        new Logoutconfirm(this, true).setVisible(true);
    }//GEN-LAST:event_CerrarSesionMousePressed

    private void Boton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton1MouseEntered
        Boton1.setBackground(new java.awt.Color(255,159,101));
    }//GEN-LAST:event_Boton1MouseEntered

    private void Boton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton1MouseExited
        Boton1.setBackground(new java.awt.Color(247,125,52));
    }//GEN-LAST:event_Boton1MouseExited

    private void Boton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton1MousePressed

    private void Boton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton2MouseEntered
        Boton2.setBackground(new java.awt.Color(255,159,101));
    }//GEN-LAST:event_Boton2MouseEntered

    private void Boton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton2MouseExited
        Boton2.setBackground(new java.awt.Color(247,125,52));
    }//GEN-LAST:event_Boton2MouseExited

    private void Boton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton2MousePressed

    private void Boton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton3MouseEntered
        Boton3.setBackground(new java.awt.Color(255,159,101));
    }//GEN-LAST:event_Boton3MouseEntered

    private void Boton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton3MouseExited
        Boton3.setBackground(new java.awt.Color(247,125,52));
    }//GEN-LAST:event_Boton3MouseExited

    private void Boton3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton3MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton3MousePressed

    private void Boton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton4MouseEntered
        Boton4.setBackground(new java.awt.Color(255,159,101));
    }//GEN-LAST:event_Boton4MouseEntered

    private void Boton4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton4MouseExited
        Boton4.setBackground(new java.awt.Color(247,125,52));
    }//GEN-LAST:event_Boton4MouseExited

    private void Boton4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton4MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton4MousePressed

    private void Boton5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton5MouseEntered
        Boton5.setBackground(new java.awt.Color(255,159,101));
    }//GEN-LAST:event_Boton5MouseEntered

    private void Boton5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton5MouseExited
        Boton5.setBackground(new java.awt.Color(247,125,52));
    }//GEN-LAST:event_Boton5MouseExited

    private void Boton5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton5MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton5MousePressed

    
    /**
     * @param args the command line arguments[247,125,52]
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogueadoAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogueadoAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogueadoAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogueadoAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogueadoAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Boton;
    private javax.swing.JPanel Boton1;
    private javax.swing.JPanel Boton2;
    private javax.swing.JPanel Boton3;
    private javax.swing.JPanel Boton4;
    private javax.swing.JPanel Boton5;
    private javax.swing.JPanel BotonSalir;
    private javax.swing.JPanel CerrarSesion;
    private javax.swing.JPanel Fondo;
    private javax.swing.JLabel Icono;
    private javax.swing.JLabel Icono1;
    private javax.swing.JLabel Icono2;
    private javax.swing.JLabel Icono3;
    private javax.swing.JLabel Icono4;
    private javax.swing.JLabel Icono5;
    private javax.swing.JPanel Logo;
    private javax.swing.JLabel Texto;
    private javax.swing.JLabel Texto1;
    private javax.swing.JLabel Texto2;
    private javax.swing.JLabel Texto3;
    private javax.swing.JLabel Texto4;
    private javax.swing.JLabel Texto5;
    private javax.swing.JLabel imagenX;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel panelLateral;
    // End of variables declaration//GEN-END:variables
}
