/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import javax.swing.ImageIcon;
import java.awt.Desktop;
import java.net.URI;
import javax.swing.JOptionPane;

/**
 *
 * @author Gabriel Cabrera
 */
public class PopupLogin extends javax.swing.JFrame {
    int xMouse,yMouse;
    /**
     * Creates new form PopupLogin
     */
    public PopupLogin() {
        setIconImage(new ImageIcon(getClass().getResource("/login/imagenes/logo_150px.png")).getImage()); //cambiar icono
        initComponents();
        this.setLocationRelativeTo(null);
        try{ 
        javax.swing.UIManager.setLookAndFeel( 
        javax.swing.UIManager.getSystemLookAndFeelClassName()); 
        }catch ( Exception e ) { } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        todoelpanel = new javax.swing.JPanel();
        BotonSalir = new javax.swing.JPanel();
        imagenX = new javax.swing.JLabel();
        barritadearriba = new javax.swing.JPanel();
        version1 = new javax.swing.JLabel();
        version = new javax.swing.JLabel();
        escritura1 = new javax.swing.JLabel();
        escritura2 = new javax.swing.JLabel();
        escritura3 = new javax.swing.JLabel();
        escritura4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ganzerrainfo = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        todoelpanel.setBackground(new java.awt.Color(66, 72, 96));
        todoelpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonSalir.setBackground(new java.awt.Color(215, 81, 81));
        BotonSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonSalirMouseExited(evt);
            }
        });

        imagenX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagenX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/imagenes/icons8_Delete_17px.png"))); // NOI18N

        javax.swing.GroupLayout BotonSalirLayout = new javax.swing.GroupLayout(BotonSalir);
        BotonSalir.setLayout(BotonSalirLayout);
        BotonSalirLayout.setHorizontalGroup(
            BotonSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagenX, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
        );
        BotonSalirLayout.setVerticalGroup(
            BotonSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagenX, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
        );

        todoelpanel.add(BotonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        barritadearriba.setBackground(new java.awt.Color(215, 81, 81));
        barritadearriba.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barritadearribaMouseDragged(evt);
            }
        });
        barritadearriba.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barritadearribaMousePressed(evt);
            }
        });

        javax.swing.GroupLayout barritadearribaLayout = new javax.swing.GroupLayout(barritadearriba);
        barritadearriba.setLayout(barritadearribaLayout);
        barritadearribaLayout.setHorizontalGroup(
            barritadearribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );
        barritadearribaLayout.setVerticalGroup(
            barritadearribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        todoelpanel.add(barritadearriba, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 10));

        version1.setFont(new java.awt.Font("Lucida Sans", 0, 11)); // NOI18N
        version1.setForeground(new java.awt.Color(255, 255, 255));
        version1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        version1.setText("v0.0.1");
        todoelpanel.add(version1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 60, 20));

        version.setFont(new java.awt.Font("Lucida Sans", 0, 11)); // NOI18N
        version.setForeground(new java.awt.Color(255, 255, 255));
        version.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        version.setText("© 2017 Ganzerra, Inc.");
        todoelpanel.add(version, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 260, 20));

        escritura1.setFont(new java.awt.Font("Lucida Sans", 0, 11)); // NOI18N
        escritura1.setForeground(new java.awt.Color(255, 255, 255));
        escritura1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        todoelpanel.add(escritura1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 320, 20));

        escritura2.setFont(new java.awt.Font("Lucida Sans", 0, 11)); // NOI18N
        escritura2.setForeground(new java.awt.Color(255, 255, 255));
        escritura2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        escritura2.setText("Código hecho en NetBeans IDE 8.2 por el equipo de");
        todoelpanel.add(escritura2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 320, 20));

        escritura3.setFont(new java.awt.Font("Lucida Sans", 0, 11)); // NOI18N
        escritura3.setForeground(new java.awt.Color(255, 255, 255));
        escritura3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        escritura3.setText("Ganzerra.");
        todoelpanel.add(escritura3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 320, 20));

        escritura4.setFont(new java.awt.Font("Lucida Sans", 0, 11)); // NOI18N
        escritura4.setForeground(new java.awt.Color(255, 255, 255));
        escritura4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        escritura4.setText("• Íconos obtenidos de icons8.com");
        todoelpanel.add(escritura4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 320, 20));

        jButton1.setText("Enviar Feedback");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        todoelpanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/imagenes/logo_55px.png"))); // NOI18N
        jLabel1.setFocusable(false);
        todoelpanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, 55));

        ganzerrainfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ganzerrainfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/imagenes/ganzerra_marcadeagua.png"))); // NOI18N
        ganzerrainfo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ganzerrainfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ganzerrainfoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ganzerrainfoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ganzerrainfoMouseExited(evt);
            }
        });
        todoelpanel.add(ganzerrainfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 170, 55));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panelimagenes/fondo.png"))); // NOI18N
        Fondo.setFocusable(false);
        todoelpanel.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 300));

        getContentPane().add(todoelpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSalirMouseClicked
        this.dispose();        // salir al clickear
    }//GEN-LAST:event_BotonSalirMouseClicked

    private void BotonSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSalirMouseEntered
        BotonSalir.setBackground(new java.awt.Color(222,114,114)); //brillo del boton de salir al tocar mouse
    }//GEN-LAST:event_BotonSalirMouseEntered

    private void BotonSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSalirMouseExited
        BotonSalir.setBackground(new java.awt.Color(215,81,81));       // se va el brillo cuando se va el mouse
    }//GEN-LAST:event_BotonSalirMouseExited

    private void barritadearribaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barritadearribaMouseDragged
        // TODO add your handling code here:
        int x=evt.getXOnScreen();               //crea una variable para usar luego en el mouse con los valores de X
        int y=evt.getYOnScreen();               //crea una variable para usar luego en el mouse con los valores Y
        this.setLocation(x-xMouse, y-yMouse);   /*a los valores anteriores que estaban basados en 0,0, se les resta los valores
        calculados debajo para así al mover, se mueva la ventana desde la posición del mouse
        */
    }//GEN-LAST:event_barritadearribaMouseDragged

    private void barritadearribaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barritadearribaMousePressed
        // TODO add your handling code here:
        xMouse=evt.getX(); //tomar posicion X y enviarlo a xMouse
        yMouse=evt.getY();  //tomar posicion Y y enviarlo a yMouse
    }//GEN-LAST:event_barritadearribaMousePressed

    private void ganzerrainfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ganzerrainfoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ganzerrainfoMouseClicked

    private void ganzerrainfoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ganzerrainfoMouseEntered
        ganzerrainfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/imagenes/ganzerra_marcadeagua.glow.png")));
    }//GEN-LAST:event_ganzerrainfoMouseEntered

    private void ganzerrainfoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ganzerrainfoMouseExited
        ganzerrainfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/imagenes/ganzerra_marcadeagua.png")));
    }//GEN-LAST:event_ganzerrainfoMouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try { //abrir página desde java, http://javaplusnet.blogspot.com.uy/2014/02/abrir-enlace-desde-un-jbutton.html
            Desktop.getDesktop().browse(new URI("http://www.iticetp.edu.uy/2/index.php"));
            this.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "No se ha podido ejecutar la acción");
            this.dispose();
            System.out.println("Error al abrir la página");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PopupLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PopupLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PopupLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PopupLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PopupLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BotonSalir;
    private javax.swing.JLabel Fondo;
    private javax.swing.JPanel barritadearriba;
    private javax.swing.JLabel escritura1;
    private javax.swing.JLabel escritura2;
    private javax.swing.JLabel escritura3;
    private javax.swing.JLabel escritura4;
    private javax.swing.JLabel ganzerrainfo;
    private javax.swing.JLabel imagenX;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel todoelpanel;
    private javax.swing.JLabel version;
    private javax.swing.JLabel version1;
    // End of variables declaration//GEN-END:variables
}
