package login;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author Gabriel Cabrera
 */
public class Registro extends javax.swing.JFrame {
    int xMouse,yMouse;
    int usuariov=0,nombrev=0,correov=0,cedulav=0,contrav=0,contrarv=0,telefonov=0,direccionv=0,contrasenav=0,contrasenarpv=0;
    int usuariolengthmin=6;
    int usuariolengthmax=15;
    int contrasenalengthmin=8;
    int contrasenalengthmax=20;
    int cedulamax=8;
    int telefonomax=9;
    int telefonomin=8;
    String contraminenviar="contrasenalengthmin";
    String contramaxenviar="contrasenalengthmax";
    Login Login= new Login();
    /**
     * Creates new form Registro
     */
    
    public Registro() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/login/imagenes/logo_150px.png")).getImage()); //cambiar icono
        logo.requestFocusInWindow(); //hacer que no se haga focus en el textfield de nombre de usuario
        contrasenia.setEchoChar((char) 0);
        contraseniarepetir.setEchoChar((char) 0);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        panelLateral = new javax.swing.JPanel();
        nombreDeUsuario = new javax.swing.JPanel();
        fieldusuario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        nombreDeUsuario1 = new javax.swing.JPanel();
        jTextField8 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        nombreCompleto = new javax.swing.JPanel();
        fieldnombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        repetirContrasena = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        contraseniarepetir = new javax.swing.JPasswordField();
        Logo = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        reiniciar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Telefono = new javax.swing.JPanel();
        telefonofield = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Direccion = new javax.swing.JPanel();
        direccionfield = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Departamentos = new javax.swing.JComboBox<>();
        botonCancelar = new javax.swing.JPanel();
        botoncancelarTexto = new javax.swing.JLabel();
        botonSiguiente = new javax.swing.JPanel();
        botonsiguienteTexto = new javax.swing.JLabel();
        dia = new javax.swing.JComboBox<>();
        mes = new javax.swing.JComboBox<>();
        ano = new javax.swing.JComboBox<>();
        cedulaDeIdentidad = new javax.swing.JPanel();
        cedulafield = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        correoElectronico = new javax.swing.JPanel();
        correofield = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        mostrarclaves = new javax.swing.JCheckBox();
        Contrasena = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        contrasenia = new javax.swing.JPasswordField();
        BotonSalir = new javax.swing.JPanel();
        imagenX = new javax.swing.JLabel();
        torta = new javax.swing.JLabel();
        incognito = new javax.swing.JLabel();
        BotonSalir1 = new javax.swing.JPanel();
        imagenX1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login - Gazerra");
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Fondo.setBackground(new java.awt.Color(48, 52, 69));
        Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelLateral.setBackground(new java.awt.Color(247, 125, 52));
        panelLateral.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelLateralMouseDragged(evt);
            }
        });
        panelLateral.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelLateralMousePressed(evt);
            }
        });

        javax.swing.GroupLayout panelLateralLayout = new javax.swing.GroupLayout(panelLateral);
        panelLateral.setLayout(panelLateralLayout);
        panelLateralLayout.setHorizontalGroup(
            panelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        panelLateralLayout.setVerticalGroup(
            panelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        Fondo.add(panelLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 10));

        nombreDeUsuario.setBackground(new java.awt.Color(255, 255, 255));
        nombreDeUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fieldusuario.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        fieldusuario.setForeground(new java.awt.Color(163, 163, 163));
        fieldusuario.setText("Nombre de usuario");
        fieldusuario.setBorder(null);
        fieldusuario.setOpaque(false);
        fieldusuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldusuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldusuarioFocusLost(evt);
            }
        });
        nombreDeUsuario.add(fieldusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 240, 50));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/imagenes/icons8_User_35px.png"))); // NOI18N
        nombreDeUsuario.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        nombreDeUsuario1.setBackground(new java.awt.Color(255, 255, 255));
        nombreDeUsuario1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(163, 163, 163));
        jTextField8.setText("Nombre de usuario");
        nombreDeUsuario1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 240, 50));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/imagenes/icons8_User_35px.png"))); // NOI18N
        nombreDeUsuario1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        nombreDeUsuario.add(nombreDeUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 290, 50));

        Fondo.add(nombreDeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 290, 50));

        nombreCompleto.setBackground(new java.awt.Color(255, 255, 255));
        nombreCompleto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fieldnombre.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        fieldnombre.setForeground(new java.awt.Color(163, 163, 163));
        fieldnombre.setText("Nombre Completo");
        fieldnombre.setBorder(null);
        fieldnombre.setOpaque(false);
        fieldnombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldnombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldnombreFocusLost(evt);
            }
        });
        nombreCompleto.add(fieldnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1, 240, 50));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/imagenes/icons8_Employee_Card_35px_2.png"))); // NOI18N
        nombreCompleto.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        Fondo.add(nombreCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 290, 50));

        repetirContrasena.setBackground(new java.awt.Color(255, 255, 255));
        repetirContrasena.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/imagenes/icons8_Key_35px.png"))); // NOI18N
        repetirContrasena.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        contraseniarepetir.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        contraseniarepetir.setForeground(new java.awt.Color(163, 163, 163));
        contraseniarepetir.setText("Repetir Contraseña");
        contraseniarepetir.setBorder(null);
        contraseniarepetir.setEchoChar('\u2022');
        contraseniarepetir.setOpaque(false);
        contraseniarepetir.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                contraseniarepetirFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                contraseniarepetirFocusLost(evt);
            }
        });
        repetirContrasena.add(contraseniarepetir, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 0, 240, 50));

        Fondo.add(repetirContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, 290, 50));

        Logo.setBackground(new java.awt.Color(247, 125, 52));
        Logo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/imagenes/logo_127px.png"))); // NOI18N
        Logo.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        reiniciar.setBackground(new java.awt.Color(255, 204, 0));
        reiniciar.setForeground(new java.awt.Color(247, 125, 52));
        reiniciar.setToolTipText("");
        reiniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reiniciarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reiniciarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                reiniciarMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Limpiar campos");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout reiniciarLayout = new javax.swing.GroupLayout(reiniciar);
        reiniciar.setLayout(reiniciarLayout);
        reiniciarLayout.setHorizontalGroup(
            reiniciarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        reiniciarLayout.setVerticalGroup(
            reiniciarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        Logo.add(reiniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 130, 50));

        Fondo.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 150, 490));

        Telefono.setBackground(new java.awt.Color(255, 255, 255));
        Telefono.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        telefonofield.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        telefonofield.setForeground(new java.awt.Color(163, 163, 163));
        telefonofield.setText("Teléfono");
        telefonofield.setBorder(null);
        telefonofield.setOpaque(false);
        telefonofield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                telefonofieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                telefonofieldFocusLost(evt);
            }
        });
        telefonofield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonofieldActionPerformed(evt);
            }
        });
        Telefono.add(telefonofield, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 240, 50));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/imagenes/icons8_Phone_28px.png"))); // NOI18N
        Telefono.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        Fondo.add(Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, 290, 50));

        Direccion.setBackground(new java.awt.Color(255, 255, 255));
        Direccion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        direccionfield.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        direccionfield.setForeground(new java.awt.Color(163, 163, 163));
        direccionfield.setText("Dirección");
        direccionfield.setBorder(null);
        direccionfield.setOpaque(false);
        direccionfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                direccionfieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                direccionfieldFocusLost(evt);
            }
        });
        Direccion.add(direccionfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 240, 50));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/imagenes/icons8_Home_28px.png"))); // NOI18N
        Direccion.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        Fondo.add(Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 210, 290, 50));

        Departamentos.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Departamentos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Departamento" }));
        Departamentos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                DepartamentosFocusGained(evt);
            }
        });
        Fondo.add(Departamentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, 290, 50));

        botonCancelar.setBackground(new java.awt.Color(229, 70, 70));
        botonCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        botoncancelarTexto.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        botoncancelarTexto.setForeground(new java.awt.Color(255, 255, 255));
        botoncancelarTexto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botoncancelarTexto.setText("Cancelar");
        botoncancelarTexto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botoncancelarTextoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botoncancelarTextoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botoncancelarTextoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout botonCancelarLayout = new javax.swing.GroupLayout(botonCancelar);
        botonCancelar.setLayout(botonCancelarLayout);
        botonCancelarLayout.setHorizontalGroup(
            botonCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botoncancelarTexto, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        botonCancelarLayout.setVerticalGroup(
            botonCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botoncancelarTexto, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        Fondo.add(botonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 420, 140, 50));

        botonSiguiente.setBackground(new java.awt.Color(51, 255, 51));
        botonSiguiente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonSiguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonSiguienteMousePressed(evt);
            }
        });

        botonsiguienteTexto.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        botonsiguienteTexto.setForeground(new java.awt.Color(255, 255, 255));
        botonsiguienteTexto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botonsiguienteTexto.setText("Aceptar");
        botonsiguienteTexto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonsiguienteTextoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonsiguienteTextoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonsiguienteTextoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout botonSiguienteLayout = new javax.swing.GroupLayout(botonSiguiente);
        botonSiguiente.setLayout(botonSiguienteLayout);
        botonSiguienteLayout.setHorizontalGroup(
            botonSiguienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonsiguienteTexto, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        botonSiguienteLayout.setVerticalGroup(
            botonSiguienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonsiguienteTexto, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        Fondo.add(botonSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 420, 140, 50));

        dia.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        dia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        Fondo.add(dia, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 280, 54, 50));

        mes.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        mes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        Fondo.add(mes, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 280, 120, 50));

        ano.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        ano.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970", "1969", "1968", "1967", "1966", "1965", "1964", "1963", "1962", "1961", "1960", "1959", "1958", "1957", "1956", "1955", "1954", "1953", "1952", "1951", "1950", "1949", "1948", "1947", "1946", "1945", "1944", "1943", "1942", "1941", "1940", "1939", "1938", "1937", "1936", "1935", "1934", "1933", "1932", "1931", "1930", "1929", "1928", "1927", "1926", "1925", "1924", "1923", "1922", "1921", "1920", "1919", "1918", "1917", "1916", "1915", "1914", "1913", "1912", "1911", "1910", "1909", "1908", "1907", "1906", "1905", "1904", "1903", "1902", "1901", "1900" }));
        Fondo.add(ano, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 280, 60, 50));

        cedulaDeIdentidad.setBackground(new java.awt.Color(255, 255, 255));
        cedulaDeIdentidad.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cedulafield.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cedulafield.setForeground(new java.awt.Color(163, 163, 163));
        cedulafield.setText("Cédula de Identidad");
        cedulafield.setBorder(null);
        cedulafield.setOpaque(false);
        cedulafield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cedulafieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cedulafieldFocusLost(evt);
            }
        });
        cedulaDeIdentidad.add(cedulafield, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 240, 50));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/imagenes/icons8_ID_Card_35px.png"))); // NOI18N
        cedulaDeIdentidad.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        Fondo.add(cedulaDeIdentidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 290, 50));

        correoElectronico.setBackground(new java.awt.Color(255, 255, 255));
        correoElectronico.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        correofield.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        correofield.setForeground(new java.awt.Color(163, 163, 163));
        correofield.setText("Correo Electrónico");
        correofield.setBorder(null);
        correofield.setOpaque(false);
        correofield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                correofieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                correofieldFocusLost(evt);
            }
        });
        correoElectronico.add(correofield, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 240, 50));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/imagenes/icons8_Email_35px.png"))); // NOI18N
        correoElectronico.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        Fondo.add(correoElectronico, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 290, 50));

        mostrarclaves.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        mostrarclaves.setSelected(true);
        mostrarclaves.setText("Mostrar contraseñas");
        mostrarclaves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarclavesActionPerformed(evt);
            }
        });
        Fondo.add(mostrarclaves, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 350, 140, 50));

        Contrasena.setBackground(new java.awt.Color(255, 255, 255));
        Contrasena.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/imagenes/icons8_Key_35px.png"))); // NOI18N
        Contrasena.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        contrasenia.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        contrasenia.setForeground(new java.awt.Color(163, 163, 163));
        contrasenia.setText("Contraseña");
        contrasenia.setBorder(null);
        contrasenia.setEchoChar('\u2022');
        contrasenia.setOpaque(false);
        contrasenia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                contraseniaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                contraseniaFocusLost(evt);
            }
        });
        contrasenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraseniaActionPerformed(evt);
            }
        });
        Contrasena.add(contrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 0, 240, 50));

        Fondo.add(Contrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 290, 50));

        BotonSalir.setBackground(new java.awt.Color(247, 125, 52));
        BotonSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonSalirMouseExited(evt);
            }
        });

        imagenX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagenX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/imagenes/icons8_Delete_17px.png"))); // NOI18N

        javax.swing.GroupLayout BotonSalirLayout = new javax.swing.GroupLayout(BotonSalir);
        BotonSalir.setLayout(BotonSalirLayout);
        BotonSalirLayout.setHorizontalGroup(
            BotonSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagenX, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
        );
        BotonSalirLayout.setVerticalGroup(
            BotonSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagenX, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
        );

        Fondo.add(BotonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, 20, 20));

        torta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/imagenes/icons8_Birthday_35px.png"))); // NOI18N
        torta.setOpaque(true);
        Fondo.add(torta, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 280, -1, 50));

        incognito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/imagenes/icons8_Anonymous_Mask_35px.png"))); // NOI18N
        incognito.setOpaque(true);
        Fondo.add(incognito, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 350, -1, 50));

        BotonSalir1.setBackground(new java.awt.Color(247, 125, 52));
        BotonSalir1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonSalir1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonSalir1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonSalir1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonSalir1MouseExited(evt);
            }
        });
        BotonSalir1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imagenX1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagenX1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/imagenes/icons8_Horizontal_Line_17px_1.png"))); // NOI18N
        imagenX1.setFocusable(false);
        BotonSalir1.add(imagenX1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 0, -1, 20));

        Fondo.add(BotonSalir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(858, 10, 22, 20));

        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelLateralMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelLateralMousePressed
        xMouse=evt.getX(); //tomar posicion X y enviarlo a xMouse
        yMouse=evt.getY();  //tomar posicion Y y enviarlo a yMouse
    }//GEN-LAST:event_panelLateralMousePressed

    private void panelLateralMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelLateralMouseDragged
        int x=evt.getXOnScreen();               //crea una variable para usar luego en el mouse con los valores de X
        int y=evt.getYOnScreen();               //crea una variable para usar luego en el mouse con los valores Y
        this.setLocation(x-xMouse, y-yMouse);        // TODO add your handling code here:
    }//GEN-LAST:event_panelLateralMouseDragged

    private void DepartamentosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DepartamentosFocusGained
    Departamentos.setBackground(new java.awt.Color(255, 255, 255));
    Departamentos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Artigas", "Canelones", "Cerro Largo", "Colonia", "Durazno", "Flores", "Florida", "Lavalleja", "Maldonado", "Montevideo", "Paysandú", "Río Negro", "Rivera", "Rocha", "Salto", "San José", "Soriano", "Tacuarembó", "Treinta y Tres" }));
    }//GEN-LAST:event_DepartamentosFocusGained

    private void telefonofieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonofieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonofieldActionPerformed

    private void fieldusuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldusuarioFocusGained
    nombreDeUsuario.setBackground(new java.awt.Color(255, 255, 255));
    if (usuariov==0){
    fieldusuario.setForeground(new java.awt.Color(30, 30, 30));
    fieldusuario.setText("");
    usuariov=1;
    }
    }//GEN-LAST:event_fieldusuarioFocusGained

    private void fieldusuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldusuarioFocusLost
    String dato;
    dato = this.fieldusuario.getText();
    if ("".equals(dato)){
        fieldusuario.setForeground(new java.awt.Color(163, 163, 163));
        fieldusuario.setText("Nombre de usuario");
        usuariov=0;
    }
    }//GEN-LAST:event_fieldusuarioFocusLost

    private void fieldnombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldnombreFocusGained
    nombreCompleto.setBackground(new java.awt.Color(255, 255, 255));
    if (nombrev==0){
    fieldnombre.setForeground(new java.awt.Color(30, 30, 30));
    fieldnombre.setText("");
    nombrev=1;
    }
    }//GEN-LAST:event_fieldnombreFocusGained

    private void fieldnombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldnombreFocusLost
    String dato;
    dato = this.fieldnombre.getText();
    if ("".equals(dato)){
        fieldnombre.setForeground(new java.awt.Color(163, 163, 163));
        fieldnombre.setText("Nombre Completo");
        nombrev=0;
    }
    }//GEN-LAST:event_fieldnombreFocusLost

    private void correofieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_correofieldFocusGained
    correoElectronico.setBackground(new java.awt.Color(255, 255, 255));
    if (correov==0){
    correofield.setForeground(new java.awt.Color(30, 30, 30));
    correofield.setText("");
    correov=1;
    }
    }//GEN-LAST:event_correofieldFocusGained

    private void correofieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_correofieldFocusLost
    String dato;
    dato = this.correofield.getText();
    if ("".equals(dato)){
        correofield.setForeground(new java.awt.Color(163, 163, 163));
        correofield.setText("Correo Electrónico");
        correov=0;
    }
    }//GEN-LAST:event_correofieldFocusLost

    private void cedulafieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cedulafieldFocusGained
    cedulaDeIdentidad.setBackground(new java.awt.Color(255, 255, 255));
    if (cedulav==0){
    cedulafield.setForeground(new java.awt.Color(30, 30, 30));
    cedulafield.setText("");
    cedulav=1;
    }
    }//GEN-LAST:event_cedulafieldFocusGained

    private void cedulafieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cedulafieldFocusLost
    String dato;
    dato = this.cedulafield.getText();
    if ("".equals(dato)){
        cedulafield.setForeground(new java.awt.Color(163, 163, 163));
        cedulafield.setText("Cédula de Identidad");
        cedulav=0;
    }
    }//GEN-LAST:event_cedulafieldFocusLost

    private void telefonofieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_telefonofieldFocusGained
    Telefono.setBackground(new java.awt.Color(255, 255, 255));
    if (telefonov==0){
    telefonofield.setForeground(new java.awt.Color(30, 30, 30));
    telefonofield.setText("");
    telefonov=1;
    }
    }//GEN-LAST:event_telefonofieldFocusGained

    private void telefonofieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_telefonofieldFocusLost
    if ("".equals(this.telefonofield.getText())){
        telefonofield.setForeground(new java.awt.Color(163, 163, 163));
        telefonofield.setText("Teléfono");
        telefonov=0;
    }
    }//GEN-LAST:event_telefonofieldFocusLost

    private void direccionfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_direccionfieldFocusGained
    Direccion.setBackground(new java.awt.Color(255, 255, 255));
    if (direccionv==0){
    direccionfield.setForeground(new java.awt.Color(30, 30, 30));
    direccionfield.setText("");
    direccionv=1;
    }
    }//GEN-LAST:event_direccionfieldFocusGained

    private void direccionfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_direccionfieldFocusLost
    if ("".equals(this.direccionfield.getText())){
        direccionfield.setForeground(new java.awt.Color(163, 163, 163));
        direccionfield.setText("Dirección");
        direccionv=0;
    }
    }//GEN-LAST:event_direccionfieldFocusLost

    private void reiniciarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reiniciarMouseEntered
    reiniciar.setBackground(new java.awt.Color(255, 221, 86));
    }//GEN-LAST:event_reiniciarMouseEntered

    private void reiniciarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reiniciarMouseExited
    reiniciar.setBackground(new java.awt.Color(255, 204, 0));
    }//GEN-LAST:event_reiniciarMouseExited

    private void reiniciarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reiniciarMousePressed
    logo.requestFocusInWindow();
    cedulaDeIdentidad.setBackground(new java.awt.Color(255, 255, 255));
    nombreCompleto.setBackground(new java.awt.Color(255, 255, 255));  
    correoElectronico.setBackground(new java.awt.Color(255, 255, 255));  
    Contrasena.setBackground(new java.awt.Color(255, 255, 255));  
    repetirContrasena.setBackground(new java.awt.Color(255, 255, 255));  
    Telefono.setBackground(new java.awt.Color(255, 255, 255));  
    Direccion.setBackground(new java.awt.Color(255, 255, 255));  
    nombreDeUsuario.setBackground(new java.awt.Color(255, 255, 255));  
    fieldusuario.setForeground(new java.awt.Color(163, 163, 163));
    fieldusuario.setText("Nombre de usuario");
    usuariov=0;
    
    fieldnombre.setForeground(new java.awt.Color(163, 163, 163));
    fieldnombre.setText("Nombre Completo");
    nombrev=0;
    
    correofield.setForeground(new java.awt.Color(163, 163, 163));
    correofield.setText("Correo Electrónico");
    correov=0;
    
    cedulafield.setForeground(new java.awt.Color(163, 163, 163));
    cedulafield.setText("Cédula de Identidad");
    cedulav=0;
    
    telefonofield.setForeground(new java.awt.Color(163, 163, 163));
    telefonofield.setText("Teléfono");
    telefonov=0;
    
    direccionfield.setForeground(new java.awt.Color(163, 163, 163));
    direccionfield.setText("Dirección");
    direccionv=0;
    
    mostrarclaves.setSelected(true);
    contrasenia.setEchoChar((char) 0);
    contraseniarepetir.setEchoChar((char) 0);
    torta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/imagenes/icons8_Anonymous_Mask_35px.png")));
    
    contrasenia.setText("Contraseña");
    contrasenia.setForeground(new java.awt.Color(163, 163, 163));
    contrasenav=0;
    
    contraseniarepetir.setText("Repetir Contraseña");
    contraseniarepetir.setForeground(new java.awt.Color(163, 163, 163));
    contrasenarpv=0;
    
    Departamentos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Departamento" }));
    Departamentos.setBackground(new java.awt.Color(255, 255, 255));
    
    dia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
    mes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
    ano.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970", "1969", "1968", "1967", "1966", "1965", "1964", "1963", "1962", "1961", "1960", "1959", "1958", "1957", "1956", "1955", "1954", "1953", "1952", "1951", "1950", "1949", "1948", "1947", "1946", "1945", "1944", "1943", "1942", "1941", "1940", "1939", "1938", "1937", "1936", "1935", "1934", "1933", "1932", "1931", "1930", "1929", "1928", "1927", "1926", "1925", "1924", "1923", "1922", "1921", "1920", "1919", "1918", "1917", "1916", "1915", "1914", "1913", "1912", "1911", "1910", "1909", "1908", "1907", "1906", "1905", "1904", "1903", "1902", "1901", "1900" }));
    Departamentos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Departamento" }));
    
    
    logo.requestFocusInWindow();
    }//GEN-LAST:event_reiniciarMousePressed

    private void botonSiguienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSiguienteMousePressed

    }//GEN-LAST:event_botonSiguienteMousePressed

    private void mostrarclavesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarclavesActionPerformed
    if (mostrarclaves.isSelected()) {
            contrasenia.setEchoChar((char) 0);
            contraseniarepetir.setEchoChar((char) 0);
            incognito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/imagenes/icons8_Anonymous_Mask_35px.png")));
        } else {
            contrasenia.setEchoChar('•');
            contraseniarepetir.setEchoChar('•');
            incognito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/imagenes/icons8_Anonymous_Mask_35px_1.png")));
    }
    }//GEN-LAST:event_mostrarclavesActionPerformed

    private void contraseniaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contraseniaFocusGained
    Contrasena.setBackground(new java.awt.Color(255, 255, 255));
    if (contrasenav==0){
    contrasenia.setForeground(new java.awt.Color(30, 30, 30));
    contrasenia.setText("");
    contrasenav=1;
    }
    }//GEN-LAST:event_contraseniaFocusGained

    private void contraseniaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contraseniaFocusLost
    String dato;
    dato = this.contrasenia.getText();
    if ("".equals(dato)){
        contrasenia.setForeground(new java.awt.Color(163, 163, 163));
        contrasenia.setText("Contraseña");
        contrasenav=0;
    }
    }//GEN-LAST:event_contraseniaFocusLost

    private void contraseniarepetirFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contraseniarepetirFocusGained
    repetirContrasena.setBackground(new java.awt.Color(255, 255, 255));
    if (contrasenarpv==0){
    contraseniarepetir.setForeground(new java.awt.Color(30, 30, 30));
    contraseniarepetir.setText("");
    contrasenarpv=1;
    }
    }//GEN-LAST:event_contraseniarepetirFocusGained

    private void contraseniarepetirFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contraseniarepetirFocusLost
    if ("".equals(this.contraseniarepetir.getText())){
        contraseniarepetir.setForeground(new java.awt.Color(163, 163, 163));
        contraseniarepetir.setText("Repetir Contraseña");
        contrasenarpv=0;
    }
    }//GEN-LAST:event_contraseniarepetirFocusLost

    private void contraseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraseniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contraseniaActionPerformed

    private void BotonSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSalirMouseClicked
        Login.setVisible(true);
        this.dispose();        // salir al clickear
    }//GEN-LAST:event_BotonSalirMouseClicked

    private void BotonSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSalirMouseEntered
        BotonSalir.setBackground(new java.awt.Color(255,159,101)); //brillo del boton de salir al tocar mouse
    }//GEN-LAST:event_BotonSalirMouseEntered

    private void BotonSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSalirMouseExited
        BotonSalir.setBackground(new java.awt.Color(247,125,52));       // se va el brillo cuando se va el mouse
    }//GEN-LAST:event_BotonSalirMouseExited

    private void botoncancelarTextoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botoncancelarTextoMouseClicked
    Login login= new Login();
    login.setVisible(true);
    this.dispose(); 
    }//GEN-LAST:event_botoncancelarTextoMouseClicked

    private void botoncancelarTextoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botoncancelarTextoMouseEntered
    botonCancelar.setBackground(new java.awt.Color(235,116,116)); 
    }//GEN-LAST:event_botoncancelarTextoMouseEntered

    private void botoncancelarTextoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botoncancelarTextoMouseExited
    botonCancelar.setBackground(new java.awt.Color(229,70,70)); 
    }//GEN-LAST:event_botoncancelarTextoMouseExited

    private void botonsiguienteTextoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonsiguienteTextoMouseClicked
    logo.requestFocusInWindow();
    cedulaDeIdentidad.setBackground(new java.awt.Color(255, 255, 255));
    nombreCompleto.setBackground(new java.awt.Color(255, 255, 255));  
    correoElectronico.setBackground(new java.awt.Color(255, 255, 255));  
    Contrasena.setBackground(new java.awt.Color(255, 255, 255));  
    repetirContrasena.setBackground(new java.awt.Color(255, 255, 255));  
    Telefono.setBackground(new java.awt.Color(255, 255, 255));  
    Direccion.setBackground(new java.awt.Color(255, 255, 255));  
    nombreDeUsuario.setBackground(new java.awt.Color(255, 255, 255));  
    Pattern Pusuario = Pattern.compile("[A-Za-z0-9]*");
    Matcher Musuario = Pusuario.matcher(this.fieldusuario.getText());
    Pattern Pcorreo = Pattern.compile("^[\\w-]+(\\.[\\w-]+)*@[A-Za-z0-9]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$");
    Matcher Mcorreo = Pcorreo.matcher(this.correofield.getText());
    Pattern Pcedula = Pattern.compile("[0-9]*");
    Matcher Mcedula = Pcedula.matcher(this.cedulafield.getText());
    Pattern Ptelefono = Pattern.compile("[0-9]*");
    Matcher Mtelefono = Ptelefono.matcher(this.telefonofield.getText());
    if ("Nombre de usuario".equals(this.fieldusuario.getText())){
        nombreDeUsuario.setBackground(new java.awt.Color(248, 180, 180));
        System.out.println("Usuario vacío");
        logo.requestFocusInWindow();
    }
    if ("Nombre Completo".equals(this.fieldnombre.getText())){
        nombreCompleto.setBackground(new java.awt.Color(248, 180, 180));
        System.out.println("Nombre completo vacío");
        logo.requestFocusInWindow();
    }
    if ("Correo Electrónico".equals(this.correofield.getText())){
        correoElectronico.setBackground(new java.awt.Color(248, 180, 180));
        System.out.println("Correo Electrónico vacío");
        logo.requestFocusInWindow();
    }
    if ("Cédula de Identidad".equals(this.cedulafield.getText())){
        cedulaDeIdentidad.setBackground(new java.awt.Color(248, 180, 180));
        System.out.println("CI vacío");
        logo.requestFocusInWindow();
    }
    if ("Teléfono".equals(this.telefonofield.getText())){
        Telefono.setBackground(new java.awt.Color(248, 180, 180));
        System.out.println("Teléfono vacío");
        logo.requestFocusInWindow();
    }
    if ("Dirección".equals(this.direccionfield.getText())){
        Direccion.setBackground(new java.awt.Color(248, 180, 180));
        System.out.println("Direccion vacío");
        logo.requestFocusInWindow();
    }
    if ("Departamento".equals(Departamentos.getSelectedItem())){
        Departamentos.setBackground(new java.awt.Color(248, 180, 180));
        System.out.println("Departamentos no seleccionado");
        logo.requestFocusInWindow();
    }
    if ("Contraseña".equals(this.contrasenia.getText())){
        Contrasena.setBackground(new java.awt.Color(248, 180, 180));
        System.out.println("Contraseña vacía");
        logo.requestFocusInWindow();
    }
    if ("Repetir Contraseña".equals(this.contraseniarepetir.getText())){
        repetirContrasena.setBackground(new java.awt.Color(248, 180, 180));
        System.out.println("Repetir contraseña vacía");
        logo.requestFocusInWindow();
    }
     if (fieldusuario.getText().equals("Nombre de usuario")){
         new Error1(this, true).setVisible(true); ///////////////////
        nombreDeUsuario.setBackground(new java.awt.Color(248, 180, 180));
        System.out.println("Por favor ingrese un nombre de usuario.");
        fieldusuario.selectAll();
     }else{
     if(Musuario.matches()){
         if (this.fieldusuario.getText().length() >= usuariolengthmin && this.fieldusuario.getText().length() <= usuariolengthmax){
         if ("Nombre Completo".equals(this.fieldnombre.getText())){
             new Error1(this, true).setVisible(true); ///////////////////
             nombreCompleto.setBackground(new java.awt.Color(248, 180, 180));
             System.out.println("Ingrese su nombre.");
         }else{
             if(Mcorreo.find()){
                 System.out.println("Correo Válido");
                 if (Mcedula.matches()){
                     if (this.cedulafield.getText().length()>=cedulamax){
                         System.out.println("Cédula válida");
                         if (this.contrasenia.getText().length()>=contrasenalengthmin && this.contrasenia.getText().length()<= contrasenalengthmax){
                             if (this.contrasenia.getText().equals(this.contraseniarepetir.getText())){
                                 if (!"Teléfono".equals(this.telefonofield.getText())){
                                   if (this.telefonofield.getText().length()>=telefonomin && this.telefonofield.getText().length()<=telefonomax){
                                       if(Mtelefono.matches()){
                                        if ("Dirección".equals(this.direccionfield.getText())){
                                        new Error1(this, true).setVisible(true); /////////////////////////
                                        Direccion.setBackground(new java.awt.Color(248, 180, 180));
                                        direccionfield.selectAll();
                                        System.out.println("Por favor ingrese una dirección.");
                                       }else{
                                        if ("Departamento".equals(Departamentos.getSelectedItem())){
                                        new Error1(this, true).setVisible(true); /////////////////////
                                        Departamentos.setBackground(new java.awt.Color(248, 180, 180));
                                        System.out.println("Por favor seleccione un departamento.");
                                        
                                        }else{
                                            //acá terminan las comprobaciones/////////////////////////////////////////////////////////////////////////////////
                                            Login.usersave.setText(fieldusuario.getText());
                                            String valorPass = new String(contrasenia.getPassword());
                                            mostrarclaves.setSelected(true);
                                            contrasenia.setEchoChar((char) 0);
                                            contraseniarepetir.setEchoChar((char) 0);
                                            Login.clavesave.setText(valorPass);
                                            Login.setVisible(true);
                                            //remplazando el primer campo con el nombre enviado de acá
                                                Login.textfielduser.setText(fieldusuario.getText());
                                                Login.primerclickuser=1;
                                                Login.textfielduser.setForeground(new java.awt.Color(30, 30, 30));
                                            this.dispose();
                                        }
                                       }
                                    }else{
                                     System.out.println("Por favor ingrese un teléfono válido.");
                                     new Error2(this, true).setVisible(true); ///////////////////
                                     telefonofield.selectAll();
                                     Telefono.setBackground(new java.awt.Color(248, 180, 180));
                                       }
                                   }else{
                                     System.out.println("Por favor ingrese un teléfono válido.");
                                     new Error2(this, true).setVisible(true); ///////////////////
                                     telefonofield.selectAll();
                                     Telefono.setBackground(new java.awt.Color(248, 180, 180));
                                   }
                                 }else{
                                     System.out.println("Por favor ingrese un teléfono.");
                                     telefonofield.selectAll();
                                     new Error1(this, true).setVisible(true);///////////////////
                                     Telefono.setBackground(new java.awt.Color(248, 180, 180));
                                 }
                             }else{
                                 System.out.println("Las contraseñas no coinciden");
                                 new Error3(this, true).setVisible(true);///////////////////
                                 contraseniarepetir.selectAll();
                                 Contrasena.setBackground(new java.awt.Color(248, 180, 180));
                                 repetirContrasena.setBackground(new java.awt.Color(248, 180, 180));
                             }
                         }else{
                             System.out.println("La contraseña debe tener "+contrasenalengthmin+" a "+contrasenalengthmax+ " carácteres.");
                             contraseniarepetir.selectAll();
                             new Error4(this, true).setVisible(true);///////////////////
                             Contrasena.setBackground(new java.awt.Color(248, 180, 180));
                             repetirContrasena.setBackground(new java.awt.Color(248, 180, 180));
                         }
                     }else{
                         System.out.println("La cedula debe tener "+cedulamax+" carácteres.");
                         cedulaDeIdentidad.setBackground(new java.awt.Color(248, 180, 180));
                         cedulafield.selectAll();
                         new Error4(this, true).setVisible(true);///////////////////
                         cedulav=0;
                     }
                 }else{
                     System.out.println("La cedula solo puede estar formada por números.");
                     cedulaDeIdentidad.setBackground(new java.awt.Color(248, 180, 180));
                     new Error5(this, true).setVisible(true);///////////////////
                     cedulafield.selectAll();
                     cedulav=0;
                     
                 }
             }else{
                 correoElectronico.setBackground(new java.awt.Color(248, 180, 180));
                 correofield.selectAll();
                 System.out.println("El correo no cumple un formato *@*.com o contiene simbolos no aceptados");
                 new Error6(this, true).setVisible(true);///////////////////
             }
             System.out.println("Usuario válido");
         }
         }else{
          nombreDeUsuario.setBackground(new java.awt.Color(248, 180, 180));
          System.out.println("El nombre de usuario debe de ser de "+usuariolengthmin+" a "+usuariolengthmax+" carácteres");
          new Error7(this, true).setVisible(true);///////////////////
         }
       }else{
        nombreDeUsuario.setBackground(new java.awt.Color(248, 180, 180));
         usuariov=0;
         fieldusuario.selectAll();
         System.out.println("El nombre de usuario sólo puede contener letras y números");
         new Error8(this, true).setVisible(true);///////////////////
     }
     }
    }//GEN-LAST:event_botonsiguienteTextoMouseClicked

    private void botonsiguienteTextoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonsiguienteTextoMouseEntered
    botonSiguiente.setBackground(new java.awt.Color(142,255,142));
    }//GEN-LAST:event_botonsiguienteTextoMouseEntered

    private void botonsiguienteTextoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonsiguienteTextoMouseExited
    botonSiguiente.setBackground(new java.awt.Color(51,255,51));
    }//GEN-LAST:event_botonsiguienteTextoMouseExited

    private void BotonSalir1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSalir1MouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_BotonSalir1MouseClicked

    private void BotonSalir1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSalir1MouseEntered
        BotonSalir1.setBackground(new java.awt.Color(255,159,101)); //brillo del boton de salir al tocar mouse
    }//GEN-LAST:event_BotonSalir1MouseEntered

    private void BotonSalir1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSalir1MouseExited
        BotonSalir1.setBackground(new java.awt.Color(247,125,52));       // se va el brillo cuando se va el mouse
    }//GEN-LAST:event_BotonSalir1MouseExited

    /**[51,255,51]
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Registro().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BotonSalir;
    private javax.swing.JPanel BotonSalir1;
    private javax.swing.JPanel Contrasena;
    private javax.swing.JComboBox<String> Departamentos;
    private javax.swing.JPanel Direccion;
    private javax.swing.JPanel Fondo;
    private javax.swing.JPanel Logo;
    private javax.swing.JPanel Telefono;
    private javax.swing.JComboBox<String> ano;
    private javax.swing.JPanel botonCancelar;
    private javax.swing.JPanel botonSiguiente;
    private javax.swing.JLabel botoncancelarTexto;
    private javax.swing.JLabel botonsiguienteTexto;
    private javax.swing.JPanel cedulaDeIdentidad;
    private javax.swing.JTextField cedulafield;
    private javax.swing.JPasswordField contrasenia;
    private javax.swing.JPasswordField contraseniarepetir;
    private javax.swing.JPanel correoElectronico;
    private javax.swing.JTextField correofield;
    private javax.swing.JComboBox<String> dia;
    private javax.swing.JTextField direccionfield;
    private javax.swing.JTextField fieldnombre;
    private javax.swing.JTextField fieldusuario;
    private javax.swing.JLabel imagenX;
    private javax.swing.JLabel imagenX1;
    private javax.swing.JLabel incognito;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JLabel logo;
    private javax.swing.JComboBox<String> mes;
    private javax.swing.JCheckBox mostrarclaves;
    private javax.swing.JPanel nombreCompleto;
    private javax.swing.JPanel nombreDeUsuario;
    private javax.swing.JPanel nombreDeUsuario1;
    private javax.swing.JPanel panelLateral;
    private javax.swing.JPanel reiniciar;
    private javax.swing.JPanel repetirContrasena;
    private javax.swing.JTextField telefonofield;
    private javax.swing.JLabel torta;
    // End of variables declaration//GEN-END:variables

    }